
title: Lane Murphy Personal Site
link: lanemurphy.github.io/about
description: Test GitHub Pages
              [About](lanemurphy.github.io/about)
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
