
title: Lane Murphy Personal Site
link: lanemurphy.github.io/about
description: <a href="http://lanemurphy.github.io/about">About Page
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
